# 載入套件

In [32]:
try:
    import tensorflow as tf
except:
    !pip install tensorflow

# 第一範例
<p> 實作 y = mx + b </p>
<p>其中x 要是為placeholder，表示我們會輸入不特定的數值</p>

In [2]:
m  = tf.constant(3.0, name="m")
b  = tf.constant(1.5, name="b")
x  = tf.placeholder(dtype="float32", name="x")

In [3]:
y = m*x + b

In [5]:
sess = tf.Session()         ## 開啟Seesion

In [6]:
## Session().run()
sess.run(y, feed_dict={x: 2}) # x 餵2

7.5

If you have a Tensor t, calling t.eval() is equivalent to calling tf.get_default_session().run(t).

In [7]:
## tensor.eval()
y.eval({x:2}, session=sess) # x 餵2

7.5

# 維度運算

In [10]:
import tensorflow as tf
M = tf.constant([[1, 2], [3, 4]], dtype="float32")
v = tf.constant([5, 6], dtype="float32")
print(M+v)           ## 查看這兩個 tensor 運算後的狀態

Tensor("add_1:0", shape=(2, 2), dtype=float32)


In [11]:
sess = tf.Session()  ## 開啟Seesion

In [12]:
sess.run(M+v)        ## 在這個 Seesion 我們去跑  tensor M 跟 v 相加

array([[ 6.,  8.],
       [ 8., 10.]], dtype=float32)

In [13]:
sess.run(M*v)        ## 在這個 Seesion 我們去跑  tensor M 跟 v 相乘

array([[ 5., 12.],
       [15., 24.]], dtype=float32)

In [14]:
## 嘗試矩陣內積，可是為什麼失敗
sess.run(tf.matmul(M,v))

ValueError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [2,2], [2].

In [28]:
## 因為要重新轉置矩陣
sess.run(tf.matmul(M, tf.reshape(v, [2,1])))

array([[17.],
       [39.]], dtype=float32)

<h3>關於 reshape

In [29]:
sess.run(tf.matmul(M, tf.reshape(v, [-1,1])))

array([[17.],
       [39.]], dtype=float32)

In [38]:
zz = tf.constant([5, 6, 10, 36 ,95 ,9556 ,26, 33], dtype="float32")
sess.run(tf.reshape(zz, [-1,2]))

array([[5.000e+00, 6.000e+00],
       [1.000e+01, 3.600e+01],
       [9.500e+01, 9.556e+03],
       [2.600e+01, 3.300e+01]], dtype=float32)